# Generated by Django 3.0.6 on 2020-06-26 17:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SPESys_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form',
            field=jsonfield.fields.JSONField(),
        ),
    ]
