# Generated by Django 3.0.6 on 2020-07-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPESys_app', '0002_auto_20200626_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='form_name',
            field=models.TextField(blank=True, default='Form', null=True),
        ),
    ]
